print('Day 1 - Python Print Function')
print('The function is declared like this:')
print("print('what to print')")
print("\n\n")
print("Hello World!\nHello World!\nHello World!")
print("\n\n")
print("Hello"+" "+"Angel")